# Generated by Django 6.0 on 2025-12-27 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('orders', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='sellers.seller'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='cars.category'),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='cars.category'),
        ),
        migrations.AddField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='cars.car'),
        ),
        migrations.AddField(
            model_name='rental',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='orders.order'),
        ),
        migrations.AddField(
            model_name='rentalavailability',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_availabilities', to='cars.car'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='cars_catego_parent__cf0d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['status'], name='cars_catego_status_160617_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price_sell'], name='cars_car_price_s_c85958_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['price_per_day'], name='cars_car_price_p_df7c78_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['category'], name='cars_car_categor_be58ea_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand'], name='cars_car_brand_i_8369a6_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['status'], name='cars_car_status_3b4442_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['car_type'], name='cars_car_car_typ_3cdda6_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['car'], name='cars_rental_car_id_0a05a7_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['pickup_date'], name='cars_rental_pickup__40f14a_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['dropoff_date'], name='cars_rental_dropoff_b0256e_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalavailability',
            index=models.Index(fields=['car'], name='cars_rental_car_id_e9358b_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalavailability',
            index=models.Index(fields=['status'], name='cars_rental_status_a287e3_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalavailability',
            index=models.Index(fields=['available_from', 'available_to'], name='cars_rental_availab_671b9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentalavailability',
            unique_together={('car', 'available_from', 'available_to')},
        ),
    ]
