# Generated by Django 6.0 on 2025-12-28 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'indexes': [models.Index(fields=['car'], name='cars_carima_car_id_55d4f2_idx'), models.Index(fields=['is_primary'], name='cars_carima_is_prim_c1e419_idx')],
            },
        ),
    ]
