# Generated by Django 6.0 on 2026-01-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
