# Generated by Django 6.0 on 2026-01-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
