# Generated by Django 6.0 on 2026-02-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image_url',
            field=models.ImageField(upload_to='cars/'),
        ),
    ]
