# Generated by Django 6.0 on 2026-02-15 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBlockDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='cars.car')),
            ],
            options={
                'unique_together': {('car', 'date')},
            },
        ),
    ]
